export const LOADING_PRODUCT = "LOADING_PRODUCT"
export const GET_PRODUCT = "GET_PRODUCT"
export const INSERT_PRODUCT = "INSERT_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const ERROR_PRODUCT = "ERROR_PRODUCT"

export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DECREMENT_COUNTER = "DECREMENT_COUNTER"